---
- hosts: vm1
  become: true
  tasks:
#  - name: 파일을 만든다
#    file:
#      path: 'testfile'
#      state: touch
#      mode: 0777

  - name: 파일을 복사한다
    copy: 
      src: 'copyTestFile' # 로컬경로여야 함
      dest: '{{ file_destination }}'

  - name: 복사된 파일을 확인한다
    find:
      path: './'
      patterns: '{{ file_destination }}'
    register: find_result

  - debug: var=find_result
